import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
// import HomeLayoutPage from '../../component/layout/layoutpage/homepage'
import { Box } from '@mui/material'
import HomeLayoutPage from '@/component/layout/layoutpage/homepage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Box>
          <HomeLayoutPage />
          {/* <Home */}
        </Box>
      </main>
    </>
  )
}
